# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  dockerId: molldevhub  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  dockerRepo: moll.dev
  imageName: pipeline  # Replace with the name of the image you want to publish


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: docker build -t $(dockerRepo)/$(imageName) docker/$(imageName)
  displayName: Building Image

- script: docker tag $(dockerRepo)/$(imageName) $(dockerId).azurecr.io/$(dockerRepo)/$(imageName)
  displayName: Tagging Image

- task: Docker@2
  displayName: Pushing Image
  inputs:
    containerRegistry: $(dockerId)
    repository: $(dockerRepo)
    command: 'push'
    tags: $(dockerId).azurecr.io/$(dockerRepo)/$(imageName)

