# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  dockerRegistry: molldevhub  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  dockerRepo: moll.dev
  imageName: pipeline  # Replace with the name of the image you want to publish


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    command: 'login'
    
- task: Docker@2
  inputs:
    containerRegistry: 'molldevhub'
    repository: 'moll.dev'
    command: 'build'
    Dockerfile: '**/docker/$(imageName)/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'molldevhub'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'molldevhub'
    repository: 'moll.dev'
    command: 'push'