# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  dockerId: molldevhub
  dockerRepo: moll.dev
  imageName: pipeline  # Replace with the name of the image you want to publish


resources:
  containers: 
  - container: pipeline
    image: $(dockerID)/$(dockerRepo):$(imageName)
    endpoint: molldevhub

container: pipeline

steps:
- script: hugo --version
  displayName: 'Run a one-line script'

