# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  dockerId: molldevhub
  dockerRepo: moll.dev
  registryUrl: $
  imageName: pipeline  # Replace with the name of the image you want to publish


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: docker build docker/$(imageName) -t $(dockerRepo)/$(imageName):$(Build.BuildId)
    displayName: Build $(dockerRepo)/$(imageName) Docker image

  - script: docker tag $(dockerRepo)/$(imageName):$(Build.BuildId) $(dockerId).azurecr.io/$(dockerRepo)/$(imageName)
    displayName: Tagging $(dockerRepo)/$(imageName) for upload

  - script: docker login -u $(dockerId) -p $(registrySecret) $(dockerId).azurecr.io/v2
    displayName: Login to Registry

  - script: docker push $(dockerId).azurecr.io/$(dockerRepo)/$(imageName)
    displayName: Push $(dockerRepo)/$(imageName)