baseURL = "https://moll.dev"
languageCode = "en-us"
title = "moll.dev"
pygmentsUseClasses = true
pluralizeListTitles = false

[params]
  homeTagline = "You just made a Hugo blog from scratch."

[markup.goldmark.renderer]
unsafe= true


[menu]
  [[menu.main]]
    identifier = "About"
    name = "About"
    title = "blog section"
    url = "/about/"
    pre = "blue-2 hl-blue-1"
    weight = 1

  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    title = "blog section"
    url = "/projects/"
    pre = "red-2 hl-red-1"
    weight = 2

  [[menu.main]]
    identifier = "Notes"
    name = "Notes"
    title = "blog section"
    url = "/notes/"
    pre = "yellow-2 hl-yellow-1"
    weight = 3