baseURL = "https://moll.dev"
languageCode = "en-us"
title = "moll.dev"
pygmentsUseClasses = true
pluralizeListTitles = false

[params]
  homeTagline = "You just made a Hugo blog from scratch."

[markup.goldmark.renderer]
unsafe= true


[menu]
  [[menu.main]]
    name = "About"
    title = "blog section"
    url = "/about/"
    pre = "blue-2"
    weight = 1

  [[menu.main]]
    name = "Projects"
    title = "blog section"
    url = "/projects/"
    pre = "red-2"
    weight = 2

  [[menu.main]]
    name = "Notes"
    title = "blog section"
    url = "/notes/"
    pre = "yellow-2"
    weight = 3